service: aws-node-express-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
